ZABBIX_VERSION_MAJOR = "5.2"
ZABBIX_VERSION_MINOR = "5.2.3"
POSTGRES_VERSION = "12"
PHP_TIMEZONE = "America/Sao_Paulo"

Vagrant.configure("2") do |config|

	config.vm.define "zabbix" do |zabbix|

		config.vm.box = "debian/buster64"

		zabbix.vm.hostname = "zabbix"
		zabbix.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 5432 , host: 5432, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 10050 , host: 10050, host_ip: "127.0.0.1"
		zabbix.vm.network "forwarded_port", guest: 10051 , host: 10051, host_ip: "127.0.0.1"

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Debian dependencies---- '
			sudo apt-get -q -y install gnupg2
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing PostgreSQL---- '
			sudo echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
			wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
			sudo apt-get -q update
			sudo apt-get -q -y install postgresql-#{POSTGRES_VERSION}
			sudo systemctl enable --now postgresql@#{POSTGRES_VERSION}-main
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Configuring and starting PostgreSQL---- '
			sudo sed -i "s/ident/md5/g" /etc/postgresql/#{POSTGRES_VERSION}/main/pg_hba.conf
			sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/#{POSTGRES_VERSION}/main/postgresql.conf
			sudo systemctl restart postgresql@#{POSTGRES_VERSION}-main

			echo '----Creating database and user---- '
			sudo -u postgres psql -c "CREATE USER zabbix WITH ENCRYPTED PASSWORD 'Z4bb1xD4t4b4s3'" 2>/dev/null
			sudo -u postgres createdb -O zabbix -E Unicode -T template0 zabbix 2>/dev/null
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Zabbix Server---- '
			cd /tmp
			wget --quiet https://repo.zabbix.com/zabbix/#{ZABBIX_VERSION_MAJOR}/debian/pool/main/z/zabbix-release/zabbix-release_#{ZABBIX_VERSION_MAJOR}-1+debian10_all.deb
			sudo dpkg -i zabbix-release_#{ZABBIX_VERSION_MAJOR}-1+debian10_all.deb
			sudo apt-get -q update
			sudo apt-get -q -y install zabbix-server-pgsql

			echo '----Creating database schema---- '
			zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql zabbix
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Configuring Zabbix Server---- '
			sudo sed -i "s/# DBHost=localhost/DBHost=localhost/" /etc/zabbix/zabbix_server.conf
			sudo sed -i "s/# DBPassword=/DBPassword=Z4bb1xD4t4b4s3/" /etc/zabbix/zabbix_server.conf
			
			echo '----Starting Zabbix Server---- '
			sudo systemctl start zabbix-server
			systemctl enable --now zabbix-server
			SHELL
			
		web_config = <<-WEBCONFIG
<?php
	$DB["TYPE"]				= "POSTGRESQL";
	$DB["SERVER"]			= "localhost";
	$DB["PORT"]				= "5432";
	$DB["DATABASE"]			= "zabbix";
	$DB["USER"]				= "zabbix";
	$DB["PASSWORD"]			= "Z4bb1xD4t4b4s3";
	$DB["SCHEMA"]			= "";
	$DB["ENCRYPTION"]		= false;
	$DB["KEY_FILE"]			= "";
	$DB["CERT_FILE"]		= "";
	$DB["CA_FILE"]			= "";
	$DB["VERIFY_HOST"]		= false;
	$DB["CIPHER_LIST"]		= "";
	$DB["VAULT_URL"]		= "";
	$DB["VAULT_DB_PATH"]	= "";
	$DB["VAULT_TOKEN"]		= "";
	$DB["DOUBLE_IEEE754"]	= true;
	$ZBX_SERVER				= "localhost";
	$ZBX_SERVER_PORT		= "10051";
	$ZBX_SERVER_NAME		= "zabbix";
	$IMAGE_FORMAT_DEFAULT	= IMAGE_FORMAT_PNG;
WEBCONFIG

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Zabbix Frontend for Nginx---- '
			sudo apt-get -q -y install zabbix-frontend-php php7.3-pgsql zabbix-nginx-conf
			
			echo '----Configuring Zabbix Frontend---- '
			echo "php_value[date.timezone] = #{PHP_TIMEZONE}" >> /etc/zabbix/php-fpm.conf
			echo '#{web_config}' > /etc/zabbix/web/zabbix.conf.php

			echo '----Configuring Zabbix Languages---- '
			mkdir -p /var/lib/locales/supported.d/
			rm -f /var/lib/locales/supported.d/local
			cat /usr/share/zabbix/include/locales.inc.php | grep display | grep true | awk '{$1=$1};1' | cut -d"'" -f 2 | sort | xargs -I '{}' bash -c 'echo "{}.UTF-8 UTF-8"' >> /etc/locale.gen
			dpkg-reconfigure --frontend noninteractive locales

			echo '----Configuring Nginx---- '
			sudo sed -i "s/#        listen          80;/        listen 80 default_server;\\n        listen [::]:80 default_server;/" /etc/zabbix/nginx.conf
			sudo sed -i "s/#        server_name     example.com;/        server_name _;/" /etc/zabbix/nginx.conf
			sudo rm /etc/nginx/sites-available/default
			sudo rm /etc/nginx/sites-enabled/default
			sudo rm /etc/nginx/conf.d/zabbix.conf
			sudo ln -s /etc/zabbix/nginx.conf /etc/nginx/sites-available/default
			sudo ln -s /etc/zabbix/nginx.conf /etc/nginx/sites-enabled/default
			
			echo '----Starting Nginx---- '
			systemctl enable --now php7.3-fpm
			systemctl enable --now nginx
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing Zabbix Agent---- '
			sudo apt-get -q -y install zabbix-agent
			
			echo '----Starting Zabbix Agent---- '
			systemctl enable --now zabbix-agent
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Installing TimescaleDB---- '
			sudo echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/timescaledb.list
			wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo apt-key add -
			sudo apt-get -q update
			sudo apt-get -q install -y timescaledb-2-postgresql-#{POSTGRES_VERSION}

			echo '----Stopping Zabbix-Server---- '
			systemctl stop zabbix-server

			echo '----Configuring TimescaleDB---- '
			sudo -u postgres timescaledb-tune -yes
			sudo systemctl restart postgresql@#{POSTGRES_VERSION}-main
			echo "CREATE EXTENSION IF NOT EXISTS timescaledb VERSION '1.7.4' CASCADE;" | sudo -u postgres psql zabbix 2>/dev/null

			echo '----Getting zabbix timescale config and appling it---- '
			cd /tmp
			wget --quiet https://cdn.zabbix.com/zabbix/sources/stable/#{ZABBIX_VERSION_MAJOR}/zabbix-#{ZABBIX_VERSION_MINOR}.tar.gz
			tar -zxvf zabbix-#{ZABBIX_VERSION_MINOR}.tar.gz zabbix-#{ZABBIX_VERSION_MINOR}/database/postgresql/timescaledb.sql
			cat ./zabbix-#{ZABBIX_VERSION_MINOR}/database/postgresql/timescaledb.sql | sudo -u zabbix psql zabbix
			
			echo '----Starting Zabbix-Server---- '
			systemctl start zabbix-server
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			echo '----Restarting Nginx---- '
			systemctl restart php7.3-fpm
			sleep 5
			systemctl restart nginx
			SHELL

		zabbix.vm.provision "shell", inline: <<-SHELL
			sudo rm -rf /var/lib/apt/lists/*
			sudo rm -rf /tmp/*
			SHELL

	end

end
  