ZABBIX_VERSION = "6.0"
POSTGRES_VERSION = "15"
LINUX_VERSION = "generic/rocky8"
SCRIPT_URL = "https://gist.githubusercontent.com/isaqueprofeta/7ac75a4f90b9d39283e51f78ae7abaca/raw/155e9a363788b10f835c3de88d2b1764fc3174f6/zabbix60_rocky8_timescaledb_nginx.sh"
DATABASE_PASSWORD = "Z4bb1xD4t4b4s3"

Vagrant.configure("2") do |config|

    config.vm.define "zabbix" do |zabbix|
  
      zabbix.vm.box = LINUX_VERSION

      zabbix.vm.hostname = "zabbix"
      zabbix.vm.network "forwarded_port", guest: 80 , host: 8080, host_ip: "127.0.0.1"
      zabbix.vm.network "forwarded_port", guest: 5432 , host: 5432, host_ip: "127.0.0.1"
      zabbix.vm.network "forwarded_port", guest: 10050 , host: 10050, host_ip: "127.0.0.1"
      zabbix.vm.network "forwarded_port", guest: 10051 , host: 10051, host_ip: "127.0.0.1"
              
      zabbix.vm.provision "shell", inline: <<-SHELL
        curl -sSL #{SCRIPT_URL} -o /tmp/zabbix60_bullseye_timescaledb_nginx.sh
        bash /tmp/zabbix60_bullseye_timescaledb_nginx.sh #{DATABASE_PASSWORD}
        SHELL

    end

end
