ZABBIX_VERSION = "6.0"
POSTGRES_VERSION = "15"
LINUX_VERSION = "almalinux/8"
SCRIPT_URL = "https://gist.githubusercontent.com/isaqueprofeta/7ac75a4f90b9d39283e51f78ae7abaca/raw/14cb30d578ea78c1a9feaa3d0dfd6312f88e9fe4/zabbix60_rocky8_timescaledb_nginx.sh"

Vagrant.configure("2") do |config|

    config.vm.define "zabbix" do |zabbix|
  
      zabbix.vm.box = LINUX_VERSION

      zabbix.vm.hostname = "zabbix"
      zabbix.vm.network "forwarded_port", guest: 80 , host: 8080, host_ip: "127.0.0.1"
      zabbix.vm.network "forwarded_port", guest: 5432 , host: 5432, host_ip: "127.0.0.1"
      zabbix.vm.network "forwarded_port", guest: 10050 , host: 10050, host_ip: "127.0.0.1"
      zabbix.vm.network "forwarded_port", guest: 10051 , host: 10051, host_ip: "127.0.0.1"
              
      zabbix.vm.provision "shell", inline: <<-SHELL
        curl -sSL #{SCRIPT_URL} -o /tmp/zabbix60_bullseye_timescaledb_nginx.sh
        bash /tmp/zabbix60_bullseye_timescaledb_nginx.sh
        SHELL

    end

end